[env]
TERM = "xterm-256color"

[font]
size = 12

[scrolling]
history = 10000

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "PageUp", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "PageDown", mods = "Control|Shift", action = "DecreaseFontSize" },
# { key = "Home", chars = "\u001b[H" }, # Required for macOS.
# { key = "End", chars = "\u001b[F" }, # Required for macOS.
{ key = "D", mods = "Alt", chars = "\u001bd" }, # Delete next word from cursor.
]

[selection]
# Selected text will be copied to the primary clipboard.
save_to_clipboard = true

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
command = { program = ".bin/open.sh", args = [ ] }
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

# Colors (Solarized Dark)

# Default colors
[colors.primary]
background = '#002b36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
